### ISSUE TITLE
Is there way of knowing the command's process id in preexec_functions?

### ISSUE THREAD

**Issue by KentVu** [D630/bpx#2]

**Comment by d630** [comment]
No, that's not possible per definition

**Comment by KentVu** [comment]
And BTW there are no postexec hooks as I can see, is that correct?

**Comment by d630** [comment]
prompt hooks can be interpreted as "postexec" hooks

**Comment by KentVu** [comment]
Thanks, I know that's prompt_command hook but that's not what I desired. 
I just want to know if there's a way to display the current running process id on the title bar. 
May be I should go parsing `ps`'s output for now.
Thanks again for your cooperation.
